In [1]:
import pandas as pd

df = pd.read_csv('明星信息1.csv', encoding='utf-8')
df.head()

d:\ProgramData\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,Unnamed: 0,name,englishname,nickname,nation,race,zodiac_tyep,blood_type,height,weight,birthsite,birthday,occupation,school,company,main_works,main_achieve,judge,judge_cut
0,0,赵丽颖,ZhaoLiying，Zanilia,丽颖 颖宝 小赵总 赵小刀 丽颖姐姐,中国,汉族,天秤座,A型,165cm,446kg,河北省廊坊市,1987年10月16日,演员 歌手,廊坊市电子信息工程学校,NaN,花千骨\n陆贞传奇\n杉杉来了\n楚乔传\n知否知否应是绿肥红瘦\n乘风破浪\n西游记女儿国,第28届中国电视金鹰奖观众喜爱的女演员\n第24届北京大学生电影节最受大学生欢迎女演员\n第...,登上纽约时代广场 赵丽颖是一位人气与实力兼具的演员。她凭借清丽可爱的外貌深得观众的喜欢，并因...,登上 纽约时代广场 赵丽颖 一位 人气 实力 兼具 演员 清丽 可爱 外貌 深得 观众 喜欢...
1,1,汪峰,NaN,NaN,中华人民共和国,汉,巨蟹座,A型,176cm,NaN,北京市丰台区,1971年06月29日,歌手 音乐人,中央音乐学院,NaN,花火\n勇敢的心\n信仰在空中飘扬\n河流\n在雨中\n飞得更高\n怒放的生命\n存在\n一...,东方风云榜最佳男歌手\n中歌榜最佳创作男歌手\n音乐风云榜最佳男歌手\nCCTV-MTV音乐...,离婚碰上天后，告白碰到恒大，汪峰注定一生被抢镜，汪峰的歌铿锵有力。（演员李晨评） 无论是词，...,离婚 碰上 天后 告白 碰到 恒大 汪峰 注定 一生 抢镜 汪峰 歌 铿锵有力 演员 李晨评...
2,2,沈腾,NaN,NaN,中国,汉族,天秤座,NaN,180cm,NaN,黑龙江省齐齐哈尔市,1979年10月23日,编剧 导演 演员,解放军艺术学院（戏剧表演系）,NaN,飞驰人生\n疯狂的外星人\n西虹市首富\n羞羞的铁拳\n夏洛特烦恼\n乌龙山伯爵,连续4年登上央视春晚\n《欢乐喜剧人》第一季冠军,沈腾写真及部分剧照 沈腾思维灵敏，语言犀利幽默，笑起来的时候，帅气的脸上不自觉地出现几条可爱...,沈腾 写真 剧照 沈腾 思维 灵敏 语言 犀利 幽默 笑 帅气 脸上 自觉 几条 可爱 褶皱...
3,3,黄秋生,AnthonyPerry,NaN,中国,中英混血,处女座,A型,180cm,75kg,香港,1961年09月02日,演员,香港演艺学院,NaN,《八仙饭店之人肉叉烧包》《伊波拉病毒》《野兽刑警》等,两届香港电影金像奖最佳男主角\n两届香港电影金紫荆奖最佳男主角\n两届香港电影评论学会最佳男...,黄秋生 是香港影坛的一个异类，在香港这样的商业土壤中能够诞生这样一位全面的实力派人物，是非常...,黄秋生 香港 影坛 异类 香港 商业 土壤 中 诞生 一位 实力派 人物 令人 庆幸 那种 ...
4,4,郑伊健,EkinCheng,伊健 伊面,中国,汉族,天秤座,B,179cm,65kg,香港,1967年10月04日,演员 歌手 艺人 明星,NaN,NaN,古惑仔\n风云雄霸天下\n第一诫\n九龙冰室\n中华英雄\n笑看风云\n天行者\n友情岁月,1996-1997年十大中文金曲全年最高销量歌手奖\n1985-2005年十大全港最高票房男...,郑伊健个人照 唯一长发而好看的男子，唱歌进步慢，但他声底好，试放多些时间去练声练唱，他便早已...,郑伊健 唯一 长发 好看 男子 唱歌 慢 声底 试放 多些 时间 练声 练唱 早已 上位 跳...

In [2]:
df.head()

,Unnamed: 0,name,englishname,nickname,nation,race,zodiac_tyep,blood_type,height,weight,birthsite,birthday,occupation,school,company,main_works,main_achieve,judge,judge_cut
0,0,赵丽颖,ZhaoLiying，Zanilia,丽颖 颖宝 小赵总 赵小刀 丽颖姐姐,中国,汉族,天秤座,A型,165cm,446kg,河北省廊坊市,1987年10月16日,演员 歌手,廊坊市电子信息工程学校,NaN,花千骨\n陆贞传奇\n杉杉来了\n楚乔传\n知否知否应是绿肥红瘦\n乘风破浪\n西游记女儿国,第28届中国电视金鹰奖观众喜爱的女演员\n第24届北京大学生电影节最受大学生欢迎女演员\n第...,登上纽约时代广场 赵丽颖是一位人气与实力兼具的演员。她凭借清丽可爱的外貌深得观众的喜欢，并因...,登上 纽约时代广场 赵丽颖 一位 人气 实力 兼具 演员 清丽 可爱 外貌 深得 观众 喜欢...
1,1,汪峰,NaN,NaN,中华人民共和国,汉,巨蟹座,A型,176cm,NaN,北京市丰台区,1971年06月29日,歌手 音乐人,中央音乐学院,NaN,花火\n勇敢的心\n信仰在空中飘扬\n河流\n在雨中\n飞得更高\n怒放的生命\n存在\n一...,东方风云榜最佳男歌手\n中歌榜最佳创作男歌手\n音乐风云榜最佳男歌手\nCCTV-MTV音乐...,离婚碰上天后，告白碰到恒大，汪峰注定一生被抢镜，汪峰的歌铿锵有力。（演员李晨评） 无论是词，...,离婚 碰上 天后 告白 碰到 恒大 汪峰 注定 一生 抢镜 汪峰 歌 铿锵有力 演员 李晨评...
2,2,沈腾,NaN,NaN,中国,汉族,天秤座,NaN,180cm,NaN,黑龙江省齐齐哈尔市,1979年10月23日,编剧 导演 演员,解放军艺术学院（戏剧表演系）,NaN,飞驰人生\n疯狂的外星人\n西虹市首富\n羞羞的铁拳\n夏洛特烦恼\n乌龙山伯爵,连续4年登上央视春晚\n《欢乐喜剧人》第一季冠军,沈腾写真及部分剧照 沈腾思维灵敏，语言犀利幽默，笑起来的时候，帅气的脸上不自觉地出现几条可爱...,沈腾 写真 剧照 沈腾 思维 灵敏 语言 犀利 幽默 笑 帅气 脸上 自觉 几条 可爱 褶皱...
3,3,黄秋生,AnthonyPerry,NaN,中国,中英混血,处女座,A型,180cm,75kg,香港,1961年09月02日,演员,香港演艺学院,NaN,《八仙饭店之人肉叉烧包》《伊波拉病毒》《野兽刑警》等,两届香港电影金像奖最佳男主角\n两届香港电影金紫荆奖最佳男主角\n两届香港电影评论学会最佳男...,黄秋生 是香港影坛的一个异类，在香港这样的商业土壤中能够诞生这样一位全面的实力派人物，是非常...,黄秋生 香港 影坛 异类 香港 商业 土壤 中 诞生 一位 实力派 人物 令人 庆幸 那种 ...
4,4,郑伊健,EkinCheng,伊健 伊面,中国,汉族,天秤座,B,179cm,65kg,香港,1967年10月04日,演员 歌手 艺人 明星,NaN,NaN,古惑仔\n风云雄霸天下\n第一诫\n九龙冰室\n中华英雄\n笑看风云\n天行者\n友情岁月,1996-1997年十大中文金曲全年最高销量歌手奖\n1985-2005年十大全港最高票房男...,郑伊健个人照 唯一长发而好看的男子，唱歌进步慢，但他声底好，试放多些时间去练声练唱，他便早已...,郑伊健 唯一 长发 好看 男子 唱歌 慢 声底 试放 多些 时间 练声 练唱 早已 上位 跳...

In [4]:
################一、通过有监督学习构建出因变量（自己知道得到的是什么）
import numpy as np

######生成年龄
df['birthyear']=df['birthday'].str.split('年')
df['birthyear1']=df['birthyear'].apply(lambda x:x[0] if x is not np.nan else '')
df['birthyear2']=pd.to_numeric(df['birthyear1'],errors='coerce')
df['age']=2020 - df['birthyear2']
df.drop(['birthyear','birthyear1','birthyear2'], axis=1, inplace=True)
#######生成代表作数量和荣誉数量
df['work_amount']=df['main_works'].str.count('\n')+1
df['achieve_amount']=df['main_achieve'].str.count('\n')+1

#######生成是否有nickname
df['is_nickname']=df['nickname'].apply(lambda x:0 if x is np.nan else 1)

#######生产occupation类别的多样性
df['occupation_amount']=df['occupation'].str.count(' ')+1

#######生成是否有慈善行为
df['achieve_charity']=df['main_achieve'].apply(lambda x:1 if '慈善' in str(x) else 0)
df['judge_charity']=df['judge'].apply(lambda x:1 if '慈善' in str(x) else 0)

df['charity'] = df.apply(lambda x:0 if (x['achieve_charity']==0) and (x['judge_charity']==0) else 1, axis=1)

#######生成获奖是否与香港相关
df['achieve_hongkong']=df['main_achieve'].apply(lambda x:1 if '香港' in str(x) else 0)

#######生成是否有春晚经历
df['achieve_chunwan']=df['main_achieve'].apply(lambda x:1 if( '春晚' or '春节联欢晚会') in str(x) else 0)

df.head()
# df.to_csv('明星信息2.csv')

,Unnamed: 0,name,englishname,nickname,nation,race,zodiac_tyep,blood_type,height,weight,...,age,work_amount,achieve_amount,is_nickname,occupation_amount,achieve_charity,judge_charity,charity,achieve_hongkong,achieve_chunwan
0,0,赵丽颖,ZhaoLiying，Zanilia,丽颖 颖宝 小赵总 赵小刀 丽颖姐姐,中国,汉族,天秤座,A型,165cm,446kg,...,33.0,7.0,5.0,1,2.0,0,0,0,0,0
1,1,汪峰,NaN,NaN,中华人民共和国,汉,巨蟹座,A型,176cm,NaN,...,49.0,10.0,20.0,0,2.0,0,0,0,0,0
2,2,沈腾,NaN,NaN,中国,汉族,天秤座,NaN,180cm,NaN,...,41.0,6.0,2.0,0,3.0,0,0,0,0,1
3,3,黄秋生,AnthonyPerry,NaN,中国,中英混血,处女座,A型,180cm,75kg,...,59.0,1.0,5.0,0,1.0,0,0,0,1,0
4,4,郑伊健,EkinCheng,伊健 伊面,中国,汉族,天秤座,B,179cm,65kg,...,53.0,8.0,10.0,1,4.0,0,0,0,0,0

## 研究明星慈善行为与声望的关系

In [5]:
charity =['慈善','爱心','捐赠','捐款','捐钱','捐助']
#var_name=['if_charity1','if_charity2','if_charity3','if_charity4','if_charity5','if_charity6']
for (i, w) in enumerate(charity):
    df['if_charity{}'.format(i)]=df['judge'].apply(lambda x:1 if str(w) in str(x) else 0)

In [2]:
charity =['慈善','爱心','捐赠','捐款','捐钱','捐助']
#var_name=['if_charity1','if_charity2','if_charity3','if_charity4','if_charity5','if_charity6']
for (i, w) in enumerate(charity):
    df['num_charity{}'.format(i)]=df['judge'].apply(lambda x: str(x).count(str(w)) )

In [7]:
df.head(20)

,Unnamed: 0,name,englishname,nickname,nation,race,zodiac_tyep,blood_type,height,weight,...,judge_charity,charity,achieve_hongkong,achieve_chunwan,if_charity0,if_charity1,if_charity2,if_charity3,if_charity4,if_charity5
0,0,赵丽颖,ZhaoLiying，Zanilia,丽颖 颖宝 小赵总 赵小刀 丽颖姐姐,中国,汉族,天秤座,A型,165cm,446kg,...,0,0,0,0,0,0,0,0,0,0
1,1,汪峰,NaN,NaN,中华人民共和国,汉,巨蟹座,A型,176cm,NaN,...,0,0,0,0,0,0,0,0,0,0
2,2,沈腾,NaN,NaN,中国,汉族,天秤座,NaN,180cm,NaN,...,0,0,0,1,0,0,0,0,0,0
3,3,黄秋生,AnthonyPerry,NaN,中国,中英混血,处女座,A型,180cm,75kg,...,0,0,1,0,0,0,0,0,0,0
4,4,郑伊健,EkinCheng,伊健 伊面,中国,汉族,天秤座,B,179cm,65kg,...,0,0,0,0,0,0,0,0,0,0
5,5,赵本山,ZhaoBenshan,本山大叔,中华人民共和国,汉族,天秤座,B型,175cm,70kg,...,0,0,0,1,0,0,0,1,0,0
6,6,董卿,DongQing,卿宝 卿姐 小董 董老师,中华人民共和国,汉族,天蝎座,NaN,169cm,50kg,...,0,0,0,0,0,0,0,0,0,0
7,7,李君妍,Aurora,华仔 露娜,中国,NaN,双鱼座,NaN,164cm,49kg,...,0,0,0,0,0,0,0,0,0,0
8,8,陈钰琪,Yukee,NaN,中国,汉族,狮子座,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
9,9,杨紫,YangZi,杨旎奥 奥奥,中国,汉族,天蝎座,A型,167cm,NaN,...,0,0,0,0,0,0,0,0,0,0
10,10,胡歌,Hugo,NaN,中国,汉族,处女座,O型,185cm,70kg,...,0,0,0,0,0,0,0,0,0,0
11,11,高亚麟,NaN,NaN,中国,汉族,巨蟹座,O型,183cm,90kg,...,0,0,0,0,0,0,0,0,0,0
12,12,任达华,SimonYam或YamTat-wah,华哥,中国,汉,双鱼座,O型,180cm,79kg,...,0,0,1,0,0,0,0,0,0,0
13,13,梁朝伟,TonyLeungChiuWai,伟爷 伟仔 老虎,中国,汉族,巨蟹座,A型,174cm,NaN,...,0,0,1,0,0,0,0,0,0,0
14,14,关晓彤,GuanXiaotong,小倾城 彤彤 双双 关关,中国,满族,处女座,O型,1724cm,NaN,...,0,0,0,0,0,0,0,0,0,0
15,15,甄子丹,DonnieYen,甄功夫,中国,汉,NaN,NaN,175cm,NaN,...,0,0,1,0,0,0,0,0,0,0
16,16,陈珈颖,KerryChan,陈欣淘,中国,汉族,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17,17,黄子恆HUGO,WongTszHang,Nick,中国,汉,巨蟹座,NaN,176cm,70kg,...,0,0,0,0,0,0,0,0,0,0
18,18,朱妍,NaN,NaN,中国,NaN,NaN,NaN,172cm,50kg,...,0,0,0,0,0,0,0,0,0,0
19,19,迪里拜尔·尤努斯,دىلبەر يۇنۇس,迪里拜尔,芬兰,维吾尔族,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [8]:
respect =['榜样','模范','典范','楷模','表率','典型','声誉','名望','名气','声名','名誉','荣誉']
var_name=['if_by','if_mf','if_df','if_km','if_bs','if_dx','if_sy','if_mw','if_mq','if_sm','if_my','if_ry']
for (w, n) in zip(respect,var_name):
    df['{}'.format(n)]=df['judge'].apply(lambda x:1 if str(w) in str(x) else 0)

In [9]:
df.head()

,Unnamed: 0,name,englishname,nickname,nation,race,zodiac_tyep,blood_type,height,weight,...,if_df,if_km,if_bs,if_dx,if_sy,if_mw,if_mq,if_sm,if_my,if_ry
0,0,赵丽颖,ZhaoLiying，Zanilia,丽颖 颖宝 小赵总 赵小刀 丽颖姐姐,中国,汉族,天秤座,A型,165cm,446kg,...,0,0,0,0,0,0,0,0,0,0
1,1,汪峰,NaN,NaN,中华人民共和国,汉,巨蟹座,A型,176cm,NaN,...,0,0,0,0,0,0,0,0,0,0
2,2,沈腾,NaN,NaN,中国,汉族,天秤座,NaN,180cm,NaN,...,0,0,0,0,0,0,0,0,0,0
3,3,黄秋生,AnthonyPerry,NaN,中国,中英混血,处女座,A型,180cm,75kg,...,0,0,0,0,0,0,0,0,0,0
4,4,郑伊健,EkinCheng,伊健 伊面,中国,汉族,天秤座,B,179cm,65kg,...,0,0,0,0,0,0,0,0,0,0

In [13]:
#######根据姓名推测性别
import ngender
#import pandas as pd

#df = pd.read_csv('明星信息5.csv', encoding='gbk')

############定义一个判断是否为中文的函数（非严格版,有一个为中文即为真）
# def is_Chinese(word):
#     for ch in word:
#         if '\u4e00'<= ch <= '\u9fff':
#             return True
#     return False
# is_Chinese('道德的aa')
############定义一个判断是否为中文的函数（严格版，有一个为非中文即为假）
def is_Chinese(word):
    for ch in word:
        if '\u4e00' > ch or ch  > '\u9fff':
            return False
    return True

# is_Chinese('道德的aa')
df['gender1']=df['name'].apply(lambda x: ngender.guess(str(x)) if is_Chinese(str(x)) is True else '')
df[['name','gender1']]

df['gender']=df['gender1'].apply(lambda x: 0 if 'female' in str(x) else 1 if 'male' in str(x)  else '')
df[['name','gender']]

# df.to_csv('明星信息5.csv')

     name gender
0     赵丽颖      0
1      汪峰      1
2      沈腾      1
3     黄秋生      1
4     郑伊健      1
...   ...    ...
2402  陈润熙      1
2403  龚海铭      1
2404  潘仪君      0
2405  韩炎达      1
2406   徐睿      1

[2407 rows x 2 columns]

In [14]:
df.to_excel('明星信息__charity1.xlsx')